### PR TITLE
bump version to 2.5.1

### PR DESCRIPTION
**Pull request by picatz**
A modern ruby version 👌

This bump helps so that `rvm` doesn't yell at me to install version `2.3.3`

### CODE REVIEW

**Comment by picatz** [comment]
I think the check failed becuase of this bug https://github.com/travis-ci/travis-ci/issues/8978

Local tests pass with `rspec`  🤷‍♂️

**Comment by busterb** [comment]
I think you wanted to also bump travis

**Comment by busterb** [comment]
Fixed and merged. Thanks @picatz, that was a weird one!

**Comment by picatz** [comment]
@busterb ❤️ ✨ No worries!

**Pull request merged**
